version: '2'

services:
  nginx-php-fpm-app:
    image: registry.selfdesign.org/docker/nginx-php-fpm:7.1-ldap
    container_name: nginx-php-fpm-app
    volumes:
    - ./data/:/www/html
    - ./logs/:/www/logs
    - /etc/localtime:/etc/localtime:ro
    environment:
    - VIRTUAL_HOST=url.hostname.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=url.hostname.com
    - LETSENCRYPT_EMAIL=user@hostname.com

    - ZABBIX_HOSTNAME=nginx-php-fpm-app-app

    - PHP_MEMORY_LIMIT=128M
    - UPLOAD_MAX_SIZE=2G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - TZ=America/Vancouver

    - LDAP_HOST=ldap://ldapserver:389
    - LDAP_BIND_DN=cn=binduser,dc=whatever,dc=org
    - LDAP_BIND_PW=surepassword
    - LDAP_BASE_DN=dc=hostname,dc=com
    - LDAP_ATTRIBUTE=uid
    - LDAP_SCOPE=sub
    - LDAP_FILTER=(objectClass=*)
    - LDAP_GROUP_ATTRIBUTE=uniquemember
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

